
name: CI
on: [push]

jobs:
    Build:
      name: Build
      runs-on: ubuntu-latest
      steps:

      - name: Set up python 3
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      
      - name: Check out code
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1
      
      - name: Run test
        run: |
          cd test && python -m unittest